MVCServis/Areas/SYADMIN/Models/MusteriTip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCServis.Areas.SYADMIN.Models
{
    public class MusteriTip
    {
        public int Id { get; set; }
        [StringLength(50)]
        public string MusteriTipi { get; set; }
        public virtual ICollection<BankoGiris> BankoGirisler { get; set; }

    }
}

MVCServis/Areas/Admin/Controllers/MusteriTipsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCServis.Areas.SYADMIN.DAL;
using MVCServis.Areas.SYADMIN.Models;

namespace MVCServis.Areas.Admin.Controllers
{
    public class MusteriTipsController : Controller
    {
        private SYADMINContext db = new SYADMINContext();

        // GET: Admin/MusteriTips
        public ActionResult Index()
        {
            return View(db.MusteriTipler.ToList());
        }

        // GET: Admin/MusteriTips/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusteriTip musteriTip = db.MusteriTipler.Find(id);
            if (musteriTip == null)
            {
                return HttpNotFound();
            }
            return View(musteriTip);
        }

        // GET: Admin/MusteriTips/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/MusteriTips/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,MusteriTipi")] MusteriTip musteriTip)
        {
            if (ModelState.IsValid)
            {
                db.MusteriTipler.Add(musteriTip);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(musteriTip);
        }

        // GET: Admin/MusteriTips/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusteriTip musteriTip = db.MusteriTipler.Find(id);
            if (musteriTip == null)
            {
                return HttpNotFound();
            }
            return View(musteriTip);
        }

        // POST: Admin/MusteriTips/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,MusteriTipi")] MusteriTip musteriTip)
        {
            if (ModelState.IsValid)
            {
                db.Entry(musteriTip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(musteriTip);
        }

        // GET: Admin/MusteriTips/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusteriTip musteriTip = db.MusteriTipler.Find(id);
            if (musteriTip == null)
            {
                return HttpNotFound();
            }
            return View(musteriTip);
        }

        // POST: Admin/MusteriTips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MusteriTip musteriTip = db.MusteriTipler.Find(id);
            db.MusteriTipler.Remove(musteriTip);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCServis/Areas/SYADMIN/Controllers/MusteriTipController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCServis.Areas.SYADMIN.DAL;
using MVCServis.Areas.SYADMIN.Models;

namespace MVCServis.Areas.SYADMIN.Controllers
{
    public class MusteriTipController : Controller
    {
        private SYADMINContext db = new SYADMINContext();

        // GET: SYADMIN/MusteriTip
        public ActionResult Index()
        {
            return View(db.MusteriTipler.ToList());
        }

        // GET: SYADMIN/MusteriTip/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusteriTip musteriTip = db.MusteriTipler.Find(id);
            if (musteriTip == null)
            {
                return HttpNotFound();
            }
            return View(musteriTip);
        }

        // GET: SYADMIN/MusteriTip/Create
        public ActionResult Create()
        {
            if (Session["Yetki"] != null && Session["Yetki"].ToString() == "1")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: SYADMIN/MusteriTip/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,MusteriTipi")] MusteriTip musteriTip)
        {
            if (ModelState.IsValid)
            {
                db.MusteriTipler.Add(musteriTip);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(musteriTip);
        }

        // GET: SYADMIN/MusteriTip/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusteriTip musteriTip = db.MusteriTipler.Find(id);
            if (musteriTip == null)
            {
                return HttpNotFound();
            }
            return View(musteriTip);
        }

        // POST: SYADMIN/MusteriTip/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,MusteriTipi")] MusteriTip musteriTip)
        {
            if (ModelState.IsValid)
            {
                db.Entry(musteriTip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(musteriTip);
        }

        // GET: SYADMIN/MusteriTip/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusteriTip musteriTip = db.MusteriTipler.Find(id);
            if (musteriTip == null)
            {
                return HttpNotFound();
            }
            return View(musteriTip);
        }

        // POST: SYADMIN/MusteriTip/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MusteriTip musteriTip = db.MusteriTipler.Find(id);
            db.MusteriTipler.Remove(musteriTip);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCServis/Areas/Admin/Views/MusteriTips/Create.cshtml
@model MVCServis.Areas.SYADMIN.Models.MusteriTip

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/SYADMIN/Views/Shared/_LayoutSYadmin.cshtml";
}

@using (Html.BeginForm("Create", "MusteriTips",
                        FormMethod.Post, new { @class = "btn-info" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Musteri Tip Oluştur</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MusteriTipi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MusteriTipi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MusteriTipi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCServis/Areas/Admin/Views/MusteriTips/Delete.cshtml
@model MVCServis.Areas.SYADMIN.Models.MusteriTip

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/SYADMIN/Views/Shared/_LayoutSYadmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MusteriTip</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MusteriTipi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MusteriTipi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCServis/Areas/Admin/Views/MusteriTips/Details.cshtml
@model MVCServis.Areas.SYADMIN.Models.MusteriTip

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/SYADMIN/Views/Shared/_LayoutSYadmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MusteriTip</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MusteriTipi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MusteriTipi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCServis/Areas/Admin/Views/MusteriTips/Edit.cshtml
@model MVCServis.Areas.SYADMIN.Models.MusteriTip

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/SYADMIN/Views/Shared/_LayoutSYadmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MusteriTip</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.MusteriTipi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MusteriTipi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MusteriTipi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCServis/Areas/Admin/Views/MusteriTips/Index.cshtml
@model IEnumerable<MVCServis.Areas.SYADMIN.Models.MusteriTip>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/SYADMIN/Views/Shared/_LayoutSYadmin.cshtml";
}

<h2>Index</h2>


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MusteriTipi)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MusteriTipi)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>